{% set name = "flyteidl" %}
{% set version = "1.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flyteidl-{{ version }}.tar.gz
  sha256: 0f3bebbdb6e20fa609d7c3ff2b1064653d299273c35d0a533d584b27b53a9a43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - googleapis-common-protos
    - protobuf >=4.21.1,<5.0.0
    - protoc-gen-swagger

test:
  imports:
    - flyteidl
    - flyteidl.admin
  commands:
    - pip check
  requires:
    - pip
    

test:
  imports:
    - flyteidl
    - validate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/flyteorg/flyteidl
  summary: IDL for Flyte Platform
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    This is one of the core repositories of Flyte. It contains the Specification 
    of the Flyte Language using protobuf messages, the Backend API specification 
    in gRPC, and Swagger REST. The repo contains the generated clients and protocol 
    message structures in multiple languages. Along with the generated code, the 
    repository also contains the Golang clients for Flyte's backend APIs (the 
    services grouped under FlyteAdmin).

    - Flyte HomePage: https://flyte.org
    - Flyte Docs: http://docs.flyte.org/

    PyPI: [https://pypi.org/project/flyteidl/](https://pypi.org/project/flyteidl/)

  doc_url: https://docs.flyte.org/projects/flyteidl/en/stable/
  dev_url: https://github.com/flyteorg/flyteidl

extra:
  recipe-maintainers:
    - bmcconeghy
    - asford
    - sugatoray
    - eapolinario
    - cosmicBboy
